defaults:
  - grasp_and_convey_table_random
  - _self_

env:
  articulation_configs:
    table:
      config:
        surfaces:
          table_surface: [ [ 0, -0.45, 0.61 ], [ 0.3, 0.25, 0.61 ] ]
    basket:
      config:
        initial_pose:
          p: [ 1.3, 0.9, 0.61 ]