defaults:
  - task: data_collection_task
  - env: desktop_pile_env
  - _self_

output_data_path: ${hydra:run.dir}/collected_data
num_episodes: 1000

task:
  _target_: robot_sim.tasks.search_task_generation.SearchAndGraspTask
  random_init_prob: 0

env:
  num_objects: 15
  robot_config:
    base_pose:
      p: [ 0.75, 0.25, 0 ]
      q: [ 0, 0, 90 ]