defaults:
  - common
  - config: articulation_common
  - config@config.model_origin_offset: sapien_pose
  - _self_

config:
  visual_path: '{MT_ASSET_DIR}/object_meshes/visual/shelf.dae'
  name: shelf
  model_origin_offset:
    p: [-0.6, 1.77, 0]
  scale: [1.0, 1.0, 0.72]

  render_material:
    metallic: 0.0
    roughness: 0.9
    specular: 0.8

  surfaces:
    _target_: collections.OrderedDict
    layer1: [[-0.35, -0.5, 0.08496], [-0.05, 0.5, 0.08496]]
    layer2: [[-0.35, -0.5, 0.51372], [-0.05, 0.5, 0.51372]]
    layer3: [[-0.35, -0.5, 0.94248], [-0.05, 0.5, 0.94248]]
    layer4: [[-0.35, -0.5, 1.37124], [-0.05, 0.5, 1.37124]]
