_target_: robot_sim.envs.basic_env.TaskBaseEnv
_recursive_: false
render_mode: human
control_mode: base_pd_pos_arm_pd_ee_abs_pose_wrt_arm_base
num_objects: 5
sim_freq: 500
obj_place_mode: random
rand_rotate_obj_around_z: true
rand_rotate_obj_xy: false
tight_factor: 1.0
articulation_configs: null
renderer: sapien
renderer_kwargs: null
shader_dir: ibl
render_config: null
enable_shadow: false
camera_cfgs: null
render_camera_cfgs: null
bg_name: null
obs_mode: image
reward_mode: null
control_freq: 5
use_room: true
random_background: false
obj_repeat_num: 1
actor_configs: null