defaults:
  - common
  - articulation_configs@articulation_configs.shelf: shelf
  - articulation_configs@articulation_configs.slide_door_container: slide_door_container
  - articulation_configs@articulation_configs.table: table
  - articulation_configs@articulation_configs.basket: basket
  - _self_

articulation_configs:
  shelf:
    available_layers: [layer2, layer3]
  slide_door_container:
    config:
      initial_pose:
        p: [2, 0, 0]
        q: [0, 0, 0, 1]
  table:
    config:
      initial_pose:
        p: [0.9, 1, 0]
        q: [0.707, 0, 0, -0.707]
      surfaces:
        table_surface: [ [ 0, -0.25, 0.61 ], [ 0.3, 0.35, 0.61 ] ]
  basket:
    config:
      initial_pose:
        p: [1, -0.4, 0]

robot_config:
  base_pose:
    p: [0.5, 0, 0]
    q: [0, 0, 180]
num_objects: 15
obj_place_mode: tight
tight_factor: 1.3
#random_background: true
obj_repeat_num: 2